require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'node_modules/**/*'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'
  - 'app/contracts/new_representation_order_contract.rb'
  - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/*'

Metrics/ParameterLists:
  Max: 6

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Exclude:
  - '**/*'

Style/ExponentialNotation:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
