{{- if .Values.webhookSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhookSecret.name }}
  labels:
    {{- include "laa-court-data-adaptor.labels" . | nindent 4 }}
type: Opaque
data:
  slack_webhook: {{ .Values.webhookSecret.value | b64enc }}
{{- end }}
